name: "Sugeng Agung Suganda"
description: "DevOps Engineer"
baseurl: ""
url: ""
twitter: "https://twitter.com/sgnd94"
profile_image_link: profile.jpg

google_analytics: ""

markdown: kramdown
permalink: /:title/
keep_files: [assets]

sass:
  style: :compressed

plugins:
  - "jemoji"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      slug: null

exclude:
  - "update_assets.sh"
  - "update_server.sh"
  - "package.json"
  - "gulpfile.js"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - ".env"
  - ".env_sample"
  - "s3_website.yml"
  - "publish.sh"
